version: 2018.1.{build}
shallow_clone: true
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'
environment:
  COVERALLS_REPO_TOKEN:
    secure: XBCyPFZbO55cEI6tMsd1Ts3O7sXF3IFCxGPYQGJbVae48G9j9miONIHmDwzG4iLG
  SONARQUBE_NEMO_TOKEN:
    secure:  ueE1C6fuPog+1+DU+hRSZrYDRPGo3yoV7q77WsPpnHpVu0cN7+wBUG+bJ+0QQ2hn
cache: .\MYOB.API.SDK\SDK\MYOB.API.SDK.snk
build_script:
- build.bat
test: off
artifacts:
- path: .\Artefacts\Nuget\Release\*.nupkg
  name: Release
- path: .\Artefacts\Nuget\Candidate\*.nupkg
  name: Candidate
- path: .\Artefacts\Coverage\output.xml
  name: Coverage
deploy:
- provider: NuGet
  api_key:
    secure: 9gL9jdoH/pCMXBOG6Be6ufT7ckozGzatc1Tla3zwNsyA/ZAi8Tb+ebVLylyv6gTv
  skip_symbols: true
  artifact: Release
  on:
    branch: release
- provider: NuGet
  api_key:
    secure: 9gL9jdoH/pCMXBOG6Be6ufT7ckozGzatc1Tla3zwNsyA/ZAi8Tb+ebVLylyv6gTv
  skip_symbols: true
  artifact: Candidate
  on:
    branch: candidate
notifications:
- provider: Webhook
  url: https://webhooks.gitter.im/e/a5f4ffd724543d128fff
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true
on_success:
- cmd: >-
    .\packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover .\Artefacts\Coverage\output.xml
